kind: AIchorManifest
apiVersion: 0.2.3
builder:
    buildArgs:
      ACCELERATOR: "cuda"
    image: jumanji-img
    dockerfile: ./Dockerfile
    context: .

spec:
    operator: kuberay
    image: jumanji-img
    # command: >
    #     python examples/train_agent.py
    command: >
        bash -c "nsys profile -f true --output=/tmp/report.qdstrm python examples/train_agent.py"
#        && python log_output_s3.py"

    debug:
        # Set to true if you want to run a jupyter notebook:
        jupyter: false

    # securityContext:
    #     # Set to true if you want to use py-spy:
    #     ptrace: false
    securityContext: # optional
        perfmon: true

    types:
        Head:
            resources:
                cpus: 4
                ramRatio: 30
                shmSizeGB: 0
                cpuLimitRatio: 1 # increase to 2 on all pods for performance boost
                accelerators: # optional
                    gpu:
                        count: 1
                        product: NVIDIA-H100-80GB-HBM3
                        type: gpu
        Workers:
            - name: workers
              count: 1
              resources:
                  cpus: 33
                  ramRatio: 4
                  shmSizeGB: 0
                  cpuLimitRatio: 1 # increase to 2 on all pods for performance boost
